spring:
    datasource:
        url: jdbc:mysql://localhost:3306/book
        username: root
        password: 2333
        driver-class-name: com.mysql.cj.jdbc.Driver

    devtools:
        restart:
            enabled: true  #设置开启热部署
            additional-paths: src/main/java #重启目录
            exclude: WEB-INF/** #排除目录
            thymeleaf:
                cache: false #使用Thymeleaf模板引擎，关闭缓存
            cache: false #关闭缓存
        format:
            enabled: true #格式化代码
        freemarker:
            cache: false #使用Freemarker模板引擎，关闭缓存
        # Redis服务器地址
    redis:
        host: localhost
        # Redis服务器端口号
        port: 6379
        # 使用的数据库索引，默认是0
        database: 0
        # 连接超时时间
        timeout: 10000s
        # 设置密码
        password: ""
        lettuce:
            pool:
                # 最大阻塞等待时间，负数表示没有限制
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 5
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中最大连接数，负数表示没有限制
                max-active: 20
#    security:
#        user:
#            name: qwer
#            password: 1234
#            roles: admin
server:
    port: 8081
